default:
	${MAKE} up

up:
	docker-compose -p elasticsearch -f docker-compose.yml up -d

down:
	docker-compose -p elasticsearch -f docker-compose.yml down --remove-orphans

reset:
	${MAKE} down
	${MAKE} up
